### PR TITLE
Try to split out tests to speed up ci

### PR DESCRIPTION
**Pull request by Licenser**
# Pull request

## Description

This tires to separate testing for different workspace components to parallelize and spend less total time

## Checklist

* [x] The RFC, if required, has been submitted and approved
* [x] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [x] The code is tested
* [x] Use of unsafe code is reasoned about in a comment
* [x] Update CHANGELOG.md appropriately, recording any changes, bug fixes, or other observable changes in behavior
* [x] The performance impact of the change is measured (see below)

## Performance

perhaps

### CODE REVIEW

**Review by mfelsche — APPROVED** [review]
It would be so cool if this makes shit faster. Hopefully the parallel compilation steps don't make it net longer.

**Comment by Licenser** [comment]
Ja I really hope it does, the test stuff right now is the slow part, if this reduces the total time for test it'd be great

**Comment by mfelsche** [comment]
The slowest part will be the connector integration tests due to the docker spinup times.

**Comment by Licenser** [comment]
This is a failed attempt, it barely affects runtime but significantly increases compute use.

**Pull request closed without merging**
