### PR TITLE
Added http stdlib module

### LINKED ISSUE #2183: `http` stdlib module
**Describe the problem you are trying to solve**

Make dealing with http in tremor easier, especially the `http` connectors: https://www.tremor.rs/docs/edge/reference/connectors/http

**Describe the solution you'd like**

An `http` module in the standard library.
It should contain:
* a submodule with common header names as constants: `std::http::headers`.
* a submodule with method names as constants: `std::http::methods`
* a submodule with common content-types as constants.
* a submodule with common status numbers and messages as constants.

And whatever you think is useful.

### PR DESCRIPTION
**Pull request by 0xquark**
Signed-off-by: Karanjot Singh <drquark@duck.com>

# Pull request

## Description
This adds http stdlib module which makes dealing with http in tremor much easier.

## Related

* [RFC](https://rfcs.tremor.rs/0000-.../)
* Related Issues: fixes #2183 
* Related [docs PR](https://github.com/tremor-rs/tremor-www-docs/pull/000)

## Checklist

* [ ] The RFC, if required, has been submitted and approved
* [ ] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [ ] The code is tested
* [ ] Use of unsafe code is reasoned about in a comment
* [ ] Update CHANGELOG.md appropriately, recording any changes, bug fixes, or other observable changes in behavior
* [ ] The performance impact of the change is measured (see below)

### CODE REVIEW

**Review by Licenser — DISMISSED** [review]
Heya very cool! That was quick :D thank you!

I'm fine with it as it is but I wonder how you feel about adding a bit of documentation to the fields so they get nicely generated as part of the docs, that way we'd get something like https://www.tremor.rs/docs/edge/reference/stdlib/cncf/otel/logs/severity

**Comment by 0xquark** [comment]
Hi @Licenser, Could you check now if it's properly implemented?

**Review by Licenser — APPROVED** [review]
Perfect, thank you so much!

**Comment by Licenser** [comment]
You are awesome :) thank you mate!

**Comment by 0xquark** [comment]
Thanks @Licenser! I've heard a lot about tremor community particularly about you that the community is awesome and contributing to tremor has been really a enjoyable experience to me :)
Looking forward to contribute to some more issues here.

**Comment by 0xquark** [comment]
@Licenser i am not sure why the tests-linux is failing here. Could you help me out here?

**Comment by Licenser** [comment]
Thank you so much for the kind words <3 we really appreciate it :) . the test failed for a timeout, not your fault I'll just restart it.

**Pull request merged**
