### PR TITLE
Mob branch for v0.9 release changes

### LINKED ISSUE #225: Patch-in-place optimization misbehaves when patch clauses use patched object
**Context**
Tremor Script features an optimization for `patch` operations by which expressions like
```tremor
let obj = patch obj of ... end;
```
can omit some copying by mutating the patched object in-place.

**Problem**
While semantically the assignment back to the original object only happens at the end of the `patch`, the `patch_in_place` optimization materializes these changes immediately. This distinction can be observed when the object being patched is used in the patch clauses.

Consider the Tremor program
```
let obj = {};
let obj = patch obj of
   insert "a" => obj,
   insert "b" => obj,
   insert "c" => obj
end;

obj
```
It should be equivalent to
```tremor
let obj = {};
let temp = patch obj of
   insert "a" => obj,
   insert "b" => obj,
   insert "c" => obj
end;

let obj = temp;

obj
```
However, the latter correctly returns `{"a": {}, "b": {}, "c": {}}`, while the former erroneously reveals the interim steps, returning `{"a": {}, "b": {"a": {}}, "c": {"a": {}, "b": {"a": {}}}}`.

**Steps**
Run the two Tremor scripts described above, and compare their outputs.

**Possible Solution(s)**
The `patch_in_place` optimization is only executed when [two conditions are met](https://github.com/wayfair-tremor/tremor-runtime/blob/8b7ee71a749957bb9240e352399b72d8a3bc4064/tremor-script/src/interpreter/expr.rs#L151-L156):
 1. the patch is on the RHS of an assignment
 2. the path of the assigned value and the path of the patched expression are identical

A third condition could be added:
 3. the patched value is not used anywhere inside the patch clauses

This would be a conservative over-approximation, but might allow you to keep the performance boost in the majority of actual uses.

### PR DESCRIPTION
**Pull request by darach**
Log of changes to prepare for release:

Must do's:
* [x] Update versions of all crate'd sub projects in cargo
* [ ] publish tremor-script 0.9
* [x] merge linked transports
* [ ] publish new language server and plugin
* [x] fix #225 via #375 
* [x] linked transport docs
* [x] unified cli docs
* [x] Document usage of in-memory WAL verses persistent
* [x] consider WAL ingest ns change (should we update it?)
* [x] Ensure errors are propagated with LT instead of the connection left hanging open (see #489 for 0.9.1)
* [x] Add codecs and preprocessors for WS linked offramp
* [x] update WS linked offramp to use reply channel code ( we can do that in 0.9.1 see #490)

Linked transport todo's:
* [ ] integration tests
* [ ] benchmarks
* [x] move current examples to workshops in docs repo (rest api, rest proxy app, rest proxy passthrough, ws echo server, ws proxy app, ws proxy passthrough)
* [x] add workshop/examples for load balancing (and failover of) rest offramps, http to websocket bridging
* [x] address the outstanding review comments from https://github.com/tremor-rs/tremor-runtime/pull/431

Wish list of unified client work to be done (copied from #426):
* [x] generating cli doc (9.1?)
* [x] improve tremor test integration
* [x] Port over api curl based tests
* [x]  Patch CI to adopt new binary for api curl based tests
* [x] Port over api based tremor cli tests
* [x]  Patch CI to adopt new binary for api tremor cli based tests
* [x]  Extend CI to support tremor stdlib unit style tests (add tests to stdlib modules)
* [x]  Extend CI to support tremor cli self hosted tests
* [ ]  Figure out code coverage against unified client
* [ ] Location reporting of script runtime errors from `run` (an example in comparison to old tremor-script binary is at https://github.com/tremor-rs/tremor-runtime/issues/445)
* [ ]  Flag to include emit port name in the script `run` output (parity with old tremor-script binary) 

Wish list for cb/wal/ack/gd:

* [ ] A Qos operator for acks, and gated acknowledgement continuations in tremor-script+query
* [ ] An operator to expose circuit-breaker events to tremor-script+query
* [ ] An operator to expose WAL events to tremor-script+query
* [ ] Consider whether qos ack/cb/wal operators are distinct, a single operator or some mix thereof ...
* [ ] Example of ack/cb/wal qos in concert with state mechanism
* [ ] Raw vs best effort ( in mem + persistent ) vs lossless/guaranteed ( recoverable ) stream detection & reporting in runtime
* [ ] Look into different WAL flavours (ringbuffer etc)
* [ ] Look into more efficient WAL encoding

Wish list for linked transport:
* [ ] introduce peer artefact/implement source and sink trait to make a linked ramp
* [ ] iron out circuit-breaker/guaranteed-delivery overlap
* [ ] cycle detection for links in binding [ DE/HG - this should wait until we kill the yaml with fire ]

Wish list for packaging:

* [ ] Fix static linking/segfault for musl binaries (reproduce via `make package-x86_64-alpine-linux-musl`). Disable musl packaging if we push this for later.
* [ ] Package validation tests as part of CI release process (installation plus running binary)
* [ ] Enable deb packaging (resolve [openssl linking](https://github.com/tremor-rs/tremor-runtime/blob/main/Makefile#L22-L28)) for it

### CODE REVIEW

**Review by Licenser — APPROVED** [review]
LGTM

**Review by darach — COMMENTED** [review]
LGTM. 👍

**Comment by anupdhml** [comment]
LGTM

**Comment by mfelsche** [comment]
Fucking finally! 🎉 🥃

**Pull request merged**
