### PR TITLE
Ensure Cargo.lock is up to date

### PR DESCRIPTION
**Pull request by Licenser**
# Pull request

## Description

Ensure that the `Cargo.lock` is always up to date in a pull request

## Checklist
* [x] The RFC, if required, has been submitted and approved
* [x] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [x] The code is tested
* [x] Use of unsafe code is reasoned about in a comment
* [x] Update CHANGELOG.md appropriately, recording any changes, bug fixes or other observable changes in behavior

### CODE REVIEW

**Comment by mfelsche** [comment]
What if we need to change the lockfile? That is when we add a dependency etc. This might break CI for dependabot too, no?

I do love the clippy part though ❤️

**Comment by mfelsche** [comment]
Ah no, got it. The build and test run should not change the Cargo.lock from what is checked into git. all good.

**Review by mfelsche — APPROVED** [review]

**Comment by Licenser** [comment]
I tested with an outdated `Cargo.lock` and it failed as expected, to keep the history clean I squashed that before the merge.

**Review by darach — APPROVED** [review]
LGTM 👍

**Pull request merged**
