### PR TITLE
Update to rust 1.54.0

### PR DESCRIPTION
**Pull request by Licenser**
# Pull request

## Description

rust update

## Checklist

* [x] The RFC, if required, has been submitted and approved
* [x] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [x] The code is tested
* [x] Use of unsafe code is reasoned about in a comment
* [x] Update CHANGELOG.md appropriately, recording any changes, bug fixes, or other observable changes in behavior
* [x] The performance impact of the change is measured (see below)

## Performance

No code changes

### CODE REVIEW

**Comment by darach** [comment]
💅  We need a special term for clippy / rustc upgrades where 99% of the changes are to appease the clippy gods but its a solid stream of `;` and `&` - It's almost `trippy pedantic` 👍

**Comment by Licenser** [comment]
We have a term, it's called my life every 3 month when a new rust hits :joy:

**Review by mfelsche — APPROVED** [review]
Me so tired after this PR!

**Review by darach — APPROVED** [review]
LGTM 🚀 

It was a trippy changeset - for the next clippy/rust upgrade we need a `needs-coffee` tag so we make sure we don't review these uncaffeinated! 1 coffee for me, 1 coffee for my eyes!

**Pull request merged**
