### PR TITLE
README update for docker resources on build

### PR DESCRIPTION
**Pull request by GaryPWhite**
# Pull request

## Description
Update language re: building with docker to call out errors folks may face if they build with less-than-recommended resources (which I totally didn't do heh)

## Checklist

* [x] The RFC, if required, has been submitted and approved
* [x] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [x] The code is tested
* [x] Use of unsafe code is reasoned about in a comment
* [x] Update CHANGELOG.md appropriately, recording any changes, bug fixes, or other observable changes in behavior
* [x] The performance impact of the change is measured (see below)

## Performance

no impact (purely cosmetic change)

### CODE REVIEW

**Review by darach — APPROVED** [review]
LGTM - Thanks for the contribution Gary 🚀

**Comment by mfelsche** [comment]
@GaryPWhite I think you need to rebase your branch on current `main`.

**Review by mfelsche — APPROVED** [review]

**Review by Licenser — APPROVED** [review]
Nice addition!

**Comment by GaryPWhite** [comment]
@mfelsche I think I did the thing right... lemme know :)

**Review by mfelsche — APPROVED** [review]

**Comment by mfelsche** [comment]
Thank you!

**Pull request merged**
