### PR TITLE
Fix: Typo Update README.md

### PR DESCRIPTION
**Pull request by bobychaudhary**
Minor typo mistake

# Pull request

## Related

* [RFC](https://rfcs.tremor.rs/0000-.../)
* Related Issues: fixes #000, closed #000
* Related [docs PR](https://github.com/tremor-rs/tremor-www-docs/pull/000)

## Checklist

* [x] The RFC, if required, has been submitted and approved
* [x] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [x] The code is tested
* [x] Use of unsafe code is reasoned about in a comment
* [x] Update CHANGELOG.md appropriately, recording any changes, bug fixes, or other observable changes in behavior
* [x] The performance impact of the change is measured (see below)

### CODE REVIEW

**Comment by Licenser** [comment]
Hi @bobychaudhary thanks for the PR, we appreciate it!

We require commits being signed off with a DCO, that blocks the merge right now, it is simple to fix so the steps are described here: https://github.com/tremor-rs/tremor-runtime/pull/1379/checks?check_run_id=4585335244 

Other then that 👍 looks great! Thanks.

**Review by Licenser — APPROVED** [review]
🚀

**Comment by bobychaudhary** [comment]
you haven't merged, is there anything left?

**Comment by Licenser** [comment]
Hi @bobychaudhary same as before the DCO signoff is missing, we'll need that to merge.

**Comment by adithyaakrishna** [comment]
@bobychaudhary Any updates on this PR? 👀 

Could you please try running these commands mentioned below?

- `git commit --amend --no-edit --signoff`
- `git push --force-with-lease origin main`

**Comment by Licenser** [comment]
Hey, @bobychaudhary since the DCO is missing since December I'll close this, for now, feel free to reopen the PR with a DCO if you get around to it.

**Pull request closed without merging**
