### PR TITLE
Fix bug that tremor run would always ever run for exactly 150s

### PR DESCRIPTION
**Pull request by Licenser**
# Pull request

## Description

Tremor run had originally a timeout running for exactly 150s, this makes no sense of all, so we join world and let the runtime decide when to stop.

## Checklist

* [x] The RFC, if required, has been submitted and approved
* [x] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [x] The code is tested
* [x] Use of unsafe code is reasoned about in a comment
* [x] Update CHANGELOG.md appropriately, recording any changes, bug fixes, or other observable changes in behavior
* [x] The performance impact of the change is measured (see below)

## Performance

no runtime changes

### CODE REVIEW

**Review by mfelsche — DISMISSED** [review]
:facepalm: lets merge this quickly, so no one sees it.

**Review by mfelsche — APPROVED** [review]

**Comment by mfelsche** [comment]
I think in this case the `codecov/patch` metric is not applicable. Those lines weren't tested before.

Would you mind adding a test for the `run_troy_source` function?

**Comment by mfelsche** [comment]
Should we add a coverage exclude for `tremor-cli`?

**Comment by Licenser** [comment]
idk that feels a bit "wrong" I want to try to see if we can use a wrapper to include more of the integration tests, that'd be really handy.

**Comment by Licenser** [comment]
Okay I got it working but cargo-llvm-cov has a limitation that prevents us from using it: https://github.com/taiki-e/cargo-llvm-cov/issues/160

**Review by mfelsche — COMMENTED** [review]
At least now we know that the tests in tremor-cli have been successful at one point in time.

**Review by mfelsche — APPROVED** [review]

**Pull request merged**
