### PR TITLE
WIP: url stlib module for parsing url struct

### LINKED ISSUE #2181: `url` stdlib module
**Describe the problem you are trying to solve**

Parsing urls as strings is hard, manipulating and evaluating them is even harder, although it doesn't have to be.

**Describe the solution you'd like**

We would like to have a stdlib module for tremor-script that makes it possible to parse a url structure from a string and construct a url from parts and modify existing urls.

Those functions would be implemented in the existing `std::url` module: 

* definitions: https://github.com/tremor-rs/tremor-runtime/blob/main/tremor-script/lib/std/url.tremor
* implementation: https://github.com/tremor-rs/tremor-runtime/blob/main/tremor-script/src/std_lib/url.rs

Example script (just my imagination going wild, could be implemented totally differently):

```
use std;
let url_str = "https://example.org/path?query=foo&snot&badger=1&badger=2#fragment";
let url = std::url::parse(url_str);
url.scheme == "https";
url.host == "example.org";
url.path = "/path";
url.query = "query=foo&snot&badger=1&badger=2";
url.fragment = "fragment";
let query = std::url::parse_query(url.query);
# ...
```

### PR DESCRIPTION
**Pull request by 0xquark**
# Pull request
## Description
This pull request includes new functionality for working with URLs in the Tremor.
The following functions have been added:

   -  url::construct: This function allows for the construction of a URL from its individual components, such as scheme, host, path, query, and fragment.

   - url::set_scheme: This function allows for the changing of the scheme of a given URL.

   -  url::set_host: This function allows for the changing of the host of a given URL.

   -  url::set_path: This function allows for the changing of the path of a given URL.

   - url::set_query: This function allows for the changing of the query of a given URL.

   - url::set_fragment: This function allows for the changing of the fragment of a given URL.

These functions are implemented using the url crate. I've attached tests but i am not able to properly verify. 

## Related

* [RFC](https://rfcs.tremor.rs/0000-.../)
* Related Issues: fixes #2181 
* Related [docs PR](https://github.com/tremor-rs/tremor-www-docs/pull/000)

## Checklist

* [ ] The RFC, if required, has been submitted and approved
* [ ] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [ ] The code is tested
* [ ] Use of unsafe code is reasoned about in a comment
* [ ] Update CHANGELOG.md appropriately, recording any changes, bug fixes, or other observable changes in behavior
* [ ] The performance impact of the change is measured (see below)

### CODE REVIEW

**Comment by Licenser** [comment]
Heya nice! that was super quick

A few suggestions:

- it'd be nice to have a `deconstruct` or `parse` function that returns a struct with fields like

```json
{
 "scheme": "https",
 "path": "/path",
...
```

- I love the `set_*` functions!  I didn't even think of that but it's sure very helpful :) it would be nice to have the opposite `get_*`
- it'd be nice to have the option to `construct` as well as parse, that takes the struct and creates a string (watch out for urlencoding ;) )
- the `set_query` / `construct` function would be nice to have the option to take a map as well as a string for the query to build a query string from it :)

**Comment by Licenser** [comment]
@0xquark are you still working on this?

**Comment by 0xquark** [comment]
Hi @Licenser!  I'm swamped right now with my work, so I couldn't move forward with this PR. 
Could you please assign another person to handle it? 
Apologies and Thanks!

**Comment by Licenser** [comment]
Closing this as there is no time to finish the PR

**Pull request closed without merging**
