### PR TITLE
Output more helpful error messages for pipeline runtime errors

### LINKED ISSUE #127: minimal value of i64 can not be expressed in tremor script
**Problem**
The literal `-9223372036854775808` can't be represented by a script

**Steps**

Run the following script:

```tremor
-9223372036854775808
```

**Notes**

Output of `tremor-server --version`: 0.7.3

### LINKED ISSUE #588: Non hygenic error with bad access in trickle
**Problem**

Followup to #587 

The script in that gives a non hygenic error but rather the message:

2020-11-13T20:20:52.823615192+00:00 ERROR tremor_runtime::pipeline - error: Error(Script(BadAccessInEvent(Range(Location { unit_id: 0, line: 77, column: 22, absolute: 1605 }, Location { unit_id: 0, line: 77, column: 37, absolute: 1620 }), Range(Location { unit_id: 0, line: 77, column: 34, absolute: 1617 }, Location { unit_id: 0, line: 77, column: 37, absolute: 1620 }), "sum", ["min", "mean", "percentiles", "count", "max"])), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })

**Steps**
Produce a access error in a trickle select

**Possible Solution(s)**
Provide hygienic errors for that. It should point to the right location in the script and provide a better error as we would have in trickle.

### PR DESCRIPTION
**Pull request by mfelsche**
# Pull request

## Description

If we have an error that is locatable within the pipeline source, we are going do display an error message, showing the error within the pipeline source.

Also:

* Added integration tests for hygienic runtime error messages
* Added possibility to add environment variables in command based tests (turns out it wasnt needed)
* Put error messages to stderr when using `tremor run`.

## Related

* Related Issues: 
* fixes #588 
* fixes #127 

## Checklist

* [x] The RFC, if required, has been submitted and approved
* [x] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [x] The code is tested
* [x] Use of unsafe code is reasoned about in a comment
* [x] Update CHANGELOG.md appropriately, recording any changes, bug fixes or other observable changes in behavior

### CODE REVIEW

**Review by Licenser — APPROVED** [review]
LGTM 👍

**Review by Licenser — DISMISSED** [review]

**Review by Licenser — DISMISSED** [review]
LGTM 👍

**Comment by Licenser** [comment]
Looks like -0.1% Coverage :(

**Comment by mfelsche** [comment]
adding some tests tomorrow morning.

**Comment by Licenser** [comment]
Let me switch the state to draft so we know it's pre-review :)

**Comment by mfelsche** [comment]
`+0.06%` take this codecov! ⚔️

**Review by Licenser — APPROVED** [review]
LGTM :+1: and <3 for the coverage increase!

**Comment by mfelsche** [comment]
Ehrensache! ❤️

**Comment by Licenser** [comment]
All tests pass and codecov status is reported, will merge since codecov is still broken :/

**Pull request merged**
