### PR TITLE
Unpack test fixtures

### PR DESCRIPTION
**Pull request by Licenser**
# Pull request

## Description

Unpack all the test fixtures for all tests

## Checklist

* [x] The RFC, if required, has been submitted and approved
* [x] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [x] The code is tested
* [x] Use of unsafe code is reasoned about in a comment
* [x] Update CHANGELOG.md appropriately, recording any changes, bug fixes, or other observable changes in behavior
* [x] The performance impact of the change is measured (see below)

## Performance

There are no code changes here

### CODE REVIEW

**Review by mfelsche — APPROVED** [review]
Thanks for doing that job!

**Comment by Licenser** [comment]
`xargs` did it for me :D

**Review by darach — APPROVED** [review]
Gargantuan bit of 💅  there! LGTM!

**Comment by darach** [comment]
Such `find tests -name '*.xz' | xargs -I {} xz -d {}` - very diff!

**Pull request merged**
