### PR TITLE
Trying to further optimize the record pattern

### PR DESCRIPTION
**Pull request by mfelsche**
# Pull request

## Description

As we have an hashmap available, i tweaked the `KnownKey` API to be able to work on those maps, so we can spare a match.

## Checklist

* [x] The RFC, if required, has been submitted and approved
* [x] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [x] The code is tested
* [x] Use of unsafe code is reasoned about in a comment
* [x] Update CHANGELOG.md appropriately, recording any changes, bug fixes, or other observable changes in behavior
* [ ] The performance impact of the change is measured (see below)

### CODE REVIEW

**Review by Licenser — APPROVED** [review]
I love it :D that should be a nice bump :rocket: I'll run benchmarks in a moment :)

Could we also back port that to simd_json's `KnownKey`?

**Comment by mfelsche** [comment]
Will do the backport this weekend :)

**Comment by mfelsche** [comment]
I think there are still a few places left where we can apply those new functions.

**Comment by Licenser** [comment]
Benchmarks say +/- 0% diff as of this entry, but the code changes are still nice :D

**Pull request merged**
