### PR TITLE
Courseware 0.9.2

### PR DESCRIPTION
**Pull request by mfelsche**
This is a leftover from the release.
Also add a release checklist so we won't forget next time.

## Checklist

* [x] The RFC, if required, has been submitted and approved
* [x] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [x] The code is tested
* [x] Use of unsafe code is reasoned about in a comment
* [x] Update CHANGELOG.md appropriately, recording any changes, bug fixes or other observable changes in behavior

### CODE REVIEW

**Review by darach — DISMISSED** [review]
LGTM

**Comment by mfelsche** [comment]
**CODECOV!!!!** :rage4:

**Review by darach — APPROVED** [review]
LGTM

**Review by Licenser — APPROVED** [review]
👍

**Pull request merged**
