### PR TITLE
Fix empty record pattern to only match records.

### PR DESCRIPTION
**Pull request by mfelsche**
# Pull request

## Related

Fixing this was faster than writing an issue.

## Checklist

* [x] The RFC, if required, has been submitted and approved
* [x] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [x] The code is tested
* [x] Use of unsafe code is reasoned about in a comment
* [x] Update CHANGELOG.md appropriately, recording any changes, bug fixes, or other observable changes in behavior
* [x] The performance impact of the change is measured (see below)

## Performance

No detectable performance impact.

### CODE REVIEW

**Comment by Licenser** [comment]
Codewise this looks good :+1: I will run a performance check on this before we merge.

**Review by darach — DISMISSED** [review]
Nice! LGTM 👍

**Comment by mfelsche** [comment]
I think I can squeeze in some tiny improvements :)

**Review by Licenser — APPROVED** [review]
I checked the perf impact, no measurable impact on our benchmarks. 0.3% decline but that is very well within the varriance

**Comment by mfelsche** [comment]
Damn, i just added a few improvements :P

**Pull request merged**
