### PR TITLE
Cleanup for lines preprocessor

### PR DESCRIPTION
**Pull request by anupdhml**
# Pull request

Cleanup lines preprocessor and add more tests for it

## Description

Fixes the panic issue reported in https://github.com/tremor-rs/tremor-runtime/issues/575.

Also removes empty event filtering coupled with the preprocessor: `remove-empty` preprocessor should be used separately now for the same result.

## Related

* Related Issues: fixes https://github.com/tremor-rs/tremor-runtime/issues/575
* Docs PR: https://github.com/tremor-rs/tremor-www-docs/pull/56

## Checklist

* [x] The RFC, if required, has been submitted and approved
* [X] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [x] The code is tested
* [x] Use of unsafe code is reasoned about in a comment

### CODE REVIEW

**Review by mfelsche — APPROVED** [review]
LGTM

**Comment by Licenser** [comment]
The change for removing the empty lines is great, but it should be reflected in the docs as it is a change in end user behaviour

**Review by Licenser — APPROVED** [review]
LGTM :+1: only leftover is the docs

**Review by darach — APPROVED** [review]
LGTM 👍

**Pull request merged**
