### PR TITLE
ci: deny warnings in ci only

### PR DESCRIPTION
**Pull request by humancalico**
Ref:
https://rust-unofficial.github.io/patterns/anti_patterns/deny-warnings.html

Signed-off-by: Akshat Agarwal <humancalico@disroot.org>

# Pull request

## Related

* [RFC](https://rfcs.tremor.rs/0000-.../)
* Related Issues: fixes #000, closed #000
* Related [docs PR](https://github.com/tremor-rs/tremor-www-docs/pull/000)

## Checklist

* [x] The RFC, if required, has been submitted and approved
* [x] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [x] The code is tested
* [x] Use of unsafe code is reasoned about in a comment
* [x] Update CHANGELOG.md appropriately, recording any changes, bug fixes, or other observable changes in behavior
* [x] The performance impact of the change is measured (see below)

### CODE REVIEW

**Comment by Licenser** [comment]
I'm not a fan of this change, what's the reasoning for only denying warnings in CI?

**Comment by humancalico** [comment]
> I'm not a fan of this change, what's the reasoning for only denying warnings in CI?

From https://rust-unofficial.github.io/patterns/anti_patterns/deny-warnings.html. 
> By disallowing the compiler to build with warnings, a crate author opts out of Rust's famed stability. Sometimes new features or old misfeatures need a change in how things are done, thus lints are written that warn for a certain grace period before being turned to deny.

**Comment by Licenser** [comment]
I can see that reasoning for crates that are published to creates.io, but most of tremor isn't. How about we remove the deny warning from those parts that are publically shared crates and keep it in the parts that aren't.

We do bind the version of rust tremor compiles with, so the problem that the article mentions isn't really one for us and I would air on the side of strictness over convenience that isn't really a convenience since we have the rust version pinned so updates always force a human to decide on them.

**Review by Licenser — CHANGES_REQUESTED** [review]
as discussed in the comments

**Comment by Licenser** [comment]
Awesome :D thank you for the work and contribution!

**Review by Licenser — APPROVED** [review]

**Pull request merged**
