### PR TITLE
Dogstatsd perf

### PR DESCRIPTION
**Pull request by Licenser**
# Pull request

## Description

Improve dogstats performance

## Checklist

* [x] The RFC, if required, has been submitted and approved
* [x] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [x] The code is tested
* [x] Use of unsafe code is reasoned about in a comment
* [x] Update CHANGELOG.md appropriately, recording any changes, bug fixes, or other observable changes in behavior
* [x] The performance impact of the change is measured (see below)

## Performance

10-20% perf improvement on parsing/rendering dogstatsd data.

### CODE REVIEW

**Review by mfelsche — APPROVED** [review]
Great stuff!
I think we could even get some more performance improvements if we use the `memchr` crate (already in dependencies) instead of `str::split_once`. We could even iterate over the `:` and `|` splits.

Also the same improvements can be applied to the `statsd` codec. As dogstatsd seems to be just an addition to plain `statsd` we could also merge both into one.

**Comment by Licenser** [comment]
Uh that's a good idea, I should give that a try. I admit I was tempted to throw in the separator detection from simd-json, but I'm not sure it's worth the effort.

**Comment by Licenser** [comment]
I am not sure how backwards compatible dogstatsd is, I think they've slightly different types and structures but on the other hand having only a single codec would be nicer

**Review by darach — APPROVED** [review]
LGTM 👍

**Review by mfelsche — APPROVED** [review]

**Pull request merged**
