### PR TITLE
Log assigned partitions on startup and rebalance

### LINKED ISSUE #846: [Kafka Onramp] Log assigned partitions on startup and rebalance
**Describe the problem you are trying to solve**

We only log partitions numbers the source/onramp is subscribed to when the partition or topic is deleted in an error message. It would be helpful to have this information visible in the logs.

**Describe the solution you'd like**
Log on `info` level the partitions the source is assigned to or gets assigned to during rebalance. Also log partitions it is no longer assigned to.

### PR DESCRIPTION
**Pull request by NamikoToriyama**
## Description
* Implement post_rebalance function
* Output partition log on info level

## Related

* Issues: fixes #846
* post_rebalance
    *  [Document](https://docs.rs/rdkafka/0.9.1/rdkafka/consumer/trait.ConsumerContext.html)
    * [Implement ref](https://dzone.com/articles/getting-started-with-kafka-and-rust-part-2)
* [rdkafka](https://github.com/fede1024/rust-rdkafka/)

## Checklist

* [x] The RFC, if required, has been submitted and approved
* [x] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [x] The code is tested
* [x] Use of unsafe code is reasoned about in a comment
* [x] Update CHANGELOG.md appropriately, recording any changes, bug fixes, or other observable changes in behavior
* [x] The performance impact of the change is measured (see below)

### CODE REVIEW

**Comment by mfelsche** [comment]
Hey, that is a cool addition to our kafka source, I like it a lot.

I just fear something has been gone wrong while bringing your branch up to speed with out main branch.
What i usually do in such situations is to note the commit hashes of my commits i want to be in the branch and then reset the branch to the current main with `git fetch origin && git reset --hard origin/main` and then I cherry pick those commits on that branch: `git cherry-pick <COMMIT_HASH>` one by one. then you can force push your branch to your fork and this PR should pick it up.

**Comment by NamikoToriyama** [comment]
Thanks for the comment.
I thought the commit was weird, I'll fix it tomorrow along with the format checks!

**Comment by Licenser** [comment]
This looks really nice! Thank you! one last request before we merge it. Could you add an entry to the `CHANGELOG.md` to make sure you get the credit for the contribution? :)

**Comment by NamikoToriyama** [comment]
Added an entry to`CHANGELOG.md`. 
I'm not good at English so please check🙏

By the way, how can I check if this feature is working?
When `make demo`, it was working fine.

**Review by mfelsche — DISMISSED** [review]

**Comment by Licenser** [comment]
Awesome thank you! This looks good, it needs a rebase because of changes in main but otherwise :rocket: good to go :D thank you so much for the contribution

**Review by Licenser — DISMISSED** [review]
Great work!

**Review by Licenser — APPROVED** [review]
:rocket:

**Comment by NamikoToriyama** [comment]
Sorry😭😭😭
The earlier one was just a merge. I tried `rebase` in this git-push.

**Comment by Licenser** [comment]
No reason to be sorry :) git is hard I get things wrong all the time!

**Review by Licenser — APPROVED** [review]

**Pull request merged**
