### PR TITLE
Redesign system_metrics test to be less dependent on timings.

### PR DESCRIPTION
**Pull request by mfelsche**
# Pull request

## Description

The system_metrics integration test failed pretty often due to timing issues. Those should be fixed with this PR.

The test has been redesigned to depend less on timings.

## Checklist

* [x] The RFC, if required, has been submitted and approved
* [x] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [x] The code is tested
* [x] Use of unsafe code is reasoned about in a comment
* [x] Update CHANGELOG.md appropriately, recording any changes, bug fixes, or other observable changes in behavior
* [x] The performance impact of the change is measured (see below)

### CODE REVIEW

**Comment by Licenser** [comment]
I'm curious what's the difference, we have contain for all 5 elements before we had a static check for all 5?

**Comment by mfelsche** [comment]
With the current integration testing tools, we can only match on exact contains of the file. They must be equal. Or we can check if it contains a certain line without order. There is not much more we can do. And this test is not testing event order, but that system metrics get produced according to `metrics_interval_s` config. I just wanted to make sure the events that caused the metrics values are present. As the system metrics can be produced with a slight delay, we might have more events in that file, so checking for exact equivalence is what was causing the instability of the test results.

**Review by darach — APPROVED** [review]
LGTM

**Review by Licenser — APPROVED** [review]
🚀

**Comment by darach** [comment]
We need a stream oriented expect style set of checks here and graceful shutdown / orderly shutdown to resolve - lets consider these for `0.next`

**Pull request merged**
